[programs.localnet]
adapter_raydium = "ADPT1q4xG8F9m64cQyjqGe11cCXQq6vL4beY5hJavhQ5"
adapter_saber = "ADPT4GbWTs9DXxo91YGBjNntYwLpXxn4gEbxfnUPfQoB"
adapter_lifinity = "ADPTF4WmNPebELw6UvnSVBdL7BAqs5ceg9tyrHsQfrJK"
adapter_orca = "ADPTTyNqameXftbqsxwXhbs7v7XP8E82YMaUStPgjmU5"
adapter_solend = "ADPTCXAFfJFVqcw73B4PWRZQjMNo7Q3Yj4g7p4zTiZnQ"
adapter_larix = "ADPTLQQ1Bwgybb2qge7QKSW7woDrhEjcLWG642qP2X4"
adapter_francium = "ADPTax5HwQ2ZWVLmceCek8UrqMhwCy5q3SHwi8W71Kv2"
adapter_katana = "ADPTwDKJTizC3V8gZXDxt5uLjJv4pBnh1nTTf9dZJnS2"
adapter_tulip = "ADPT9nhC1asRcEB13FKymLTatqWGCuZHDznGgnakWKxW"
adapter_friktion = "ADPTzbsaBdXA3FqXoPHjaTjPfh9kadxxFKxonZihP1Ji"
adapter_nft_finance = "ADPTyBr92sBCE1hdYBRvXbMpF4hKs17xyDjFPxopcsrh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "https://api.mainnet-beta.solana.com"
# cluster = "https://ssc-dao.genesysgo.net"
# cluster = "https://solana-api.tt-prod.net"
# cluster = "https://solana-api.projectserum.com"
# cluster = "https://rpc-mainnet-fork.dappio.xyz"
cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
